### PR TITLE
Update to v0.4.2

### PR DESCRIPTION
**Pull request by ykzts**
support [`prop-types`](https://www.npmjs.com/package/prop-types).

### CODE REVIEW

**Comment by mijamo** [comment]
I plan to take some time on my free time this week end to go a bit further, I will see if I can merge this at that moment. Thanks for the pull request.

**Comment by andrewsuzuki** [comment]
Bump, it would be nice to get the prop-types warning out of my console.

**Comment by sorin-davidoi** [comment]
This is really needed for people who want to test / upgrade to React 16 :+1:

**Comment by mijamo** [comment]
Sorry I took much longer than expected but I actually implemented it already in 8e2db45ca22c03a2cfcd7ee3b60158466e2be63e so it is now safe to use with React 16.

I thought this fork was just a temporary solution but it seems like it is getting quite used so I might refactor it further on and publish it under a new name on NPM to make things easier.

**Pull request closed without merging**
